<a href="https://colab.research.google.com/github/Franc91/machine_learning_course/blob/main/supervised/01_basics/03_feature_extraction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### scikit-learn
Strona biblioteki: [https://scikit-learn.org](https://scikit-learn.org)  

Dokumentacja/User Guide: [https://scikit-learn.org/stable/user_guide.html](https://scikit-learn.org/stable/user_guide.html)

Podstawowa biblioteka do uczenia maszynowego w języku Python.

Aby zainstalować bibliotekę scikit-learn, użyj polecenia poniżej:
```
!pip install scikit-learn
```
Aby zaktualizować do najnowszej wersji bibliotekę scikit-learn, użyj polecenia poniżej:
```
!pip install --upgrade scikit-learn
```
Kurs stworzony w oparciu o wersję `0.22.1`

### Spis treści:
1. [Import bibliotek](#0)
2. [Załadowanie danych](#1)
3. [Utworzenie kopii danych](#2)
4. [Generowanie nowych zmiennych](#3)
5. [Dyskretyzacja zmiennej ciągłej](#4)
6. [Ekstrakcja cech](#5)

### <a name='0'></a> Import bibliotek

In [2]:
import numpy as np
import pandas as pd
import sklearn

sklearn.__version__

'1.6.1'

### <a name='1'></a> Załadowanie danych

In [36]:
def fetch_financial_data(company='AMZN'):
    """
    This function fetches stock market quotations.
    """

    import datetime
    import yfinance as yf

    start_date = datetime.datetime(2020, 1, 1)
    end_date = datetime.datetime(2024, 1, 1)

    # Use yfinance directly
    ticker = yf.Ticker(company)
    df = ticker.history(start=start_date, end=end_date)

    # Capitalize column names for consistency with pandas_datareader output
    df.columns = [col.capitalize() for col in df.columns]

    return df

df_raw = fetch_financial_data()
df_raw.head()

,Open,High,Low,Close,Volume,Dividends,Stock splits
Date,,,,,,,
2020-01-02 00:00:00-05:00,93.750000,94.900497,93.207497,94.900497,80580000,0.0,0.0
2020-01-03 00:00:00-05:00,93.224998,94.309998,93.224998,93.748497,75288000,0.0,0.0
2020-01-06 00:00:00-05:00,93.000000,95.184502,93.000000,95.143997,81236000,0.0,0.0
2020-01-07 00:00:00-05:00,95.224998,95.694504,94.601997,95.343002,80898000,0.0,0.0
2020-01-08 00:00:00-05:00,94.902000,95.550003,94.321999,94.598503,70160000,0.0,0.0

### <a name='2'></a> Utworzenie kopii danych

In [37]:
df = df_raw.copy()
df = df[:5]
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 5 entries, 2020-01-02 00:00:00-05:00 to 2020-01-08 00:00:00-05:00
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Open          5 non-null      float64
 1   High          5 non-null      float64
 2   Low           5 non-null      float64
 3   Close         5 non-null      float64
 4   Volume        5 non-null      int64
 5   Dividends     5 non-null      float64
 6   Stock splits  5 non-null      float64
dtypes: float64(6), int64(1)
memory usage: 320.0 bytes

### <a name='3'></a> Generowanie nowych zmiennych

In [38]:
df['day'] = df.index.day
df['month'] = df.index.month
df['year'] = df.index.year
df

,Open,High,Low,Close,Volume,Dividends,Stock splits,day,month,year
Date,,,,,,,,,,
2020-01-02 00:00:00-05:00,93.750000,94.900497,93.207497,94.900497,80580000,0.0,0.0,2,1,2020
2020-01-03 00:00:00-05:00,93.224998,94.309998,93.224998,93.748497,75288000,0.0,0.0,3,1,2020
2020-01-06 00:00:00-05:00,93.000000,95.184502,93.000000,95.143997,81236000,0.0,0.0,6,1,2020
2020-01-07 00:00:00-05:00,95.224998,95.694504,94.601997,95.343002,80898000,0.0,0.0,7,1,2020
2020-01-08 00:00:00-05:00,94.902000,95.550003,94.321999,94.598503,70160000,0.0,0.0,8,1,2020

### <a name='4'></a> Dyskretyzacja zmiennej ciągłej

In [47]:
import pandas as pd
df = pd.DataFrame(data={'height': [175., 178.5, 185., 191., 184.5, 183., 168.]})
df

   height
0   175.0
1   178.5
2   185.0
3   191.0
4   184.5
5   183.0
6   168.0

In [48]:
df['height_cat'] = pd.cut(x=df.height, bins=3)
df

   height          height_cat
0   175.0  (167.977, 175.667]
1   178.5  (175.667, 183.333]
2   185.0    (183.333, 191.0]
3   191.0    (183.333, 191.0]
4   184.5    (183.333, 191.0]
5   183.0  (175.667, 183.333]
6   168.0  (167.977, 175.667]

In [49]:
df['height_cat'] = pd.cut(x=df.height, bins=(160, 175, 180, 195))
df

   height  height_cat
0   175.0  (160, 175]
1   178.5  (175, 180]
2   185.0  (180, 195]
3   191.0  (180, 195]
4   184.5  (180, 195]
5   183.0  (180, 195]
6   168.0  (160, 175]

In [50]:
df['height_cat'] = pd.cut(x=df.height, bins=(160, 175, 180, 195), labels=['small', 'medium', 'high'])
df

   height height_cat
0   175.0      small
1   178.5     medium
2   185.0       high
3   191.0       high
4   184.5       high
5   183.0       high
6   168.0      small

In [51]:
pd.get_dummies(df, drop_first=True, prefix='height')

   height  height_medium  height_high
0   175.0          False        False
1   178.5           True        False
2   185.0          False         True
3   191.0          False         True
4   184.5          False         True
5   183.0          False         True
6   168.0          False        False

### <a name='5'></a> Ekstrakcja cech

In [57]:
df = pd.DataFrame(data={'lang': [['PL', 'ENG'], ['GER', 'ENG', 'PL', 'FRA'], ['RUS']]})
df

                  lang
0            [PL, ENG]
1  [GER, ENG, PL, FRA]
2                [RUS]

In [58]:
df['lang_number'] = df['lang'].apply(len)
df

                  lang  lang_number
0            [PL, ENG]            2
1  [GER, ENG, PL, FRA]            4
2                [RUS]            1

In [59]:
df['PL_flag'] = df['lang'].apply(lambda x: 1 if 'PL' in x else 0)
df

                  lang  lang_number  PL_flag
0            [PL, ENG]            2        1
1  [GER, ENG, PL, FRA]            4        1
2                [RUS]            1        0

In [60]:
df = pd.DataFrame(data={'website': ['wp.pl', 'onet.pl', 'google.com']})
df

      website
0       wp.pl
1     onet.pl
2  google.com

In [61]:
df.website.str.split('.', expand=True)

        0    1
0      wp   pl
1    onet   pl
2  google  com

In [62]:
new = df.website.str.split('.', expand=True)
df['portal'] = new[0]
df['extension'] = new[1]
df

      website  portal extension
0       wp.pl      wp        pl
1     onet.pl    onet        pl
2  google.com  google       com